density_based_scatterplot(
  out_dir = system.file("extdata", package = "ChIPbinner"),
  genome_assembly = "hg38",
  are_R_objects = TRUE,
  output_filename = "complete",
  wildtype_samp_norm_bw = system.file("extdata/data",
                                      "Cal27_WT_H3K36me2_10kb_norm_bw.rda",
                                      package = "ChIPbinner"),
  treated_samp_norm_bw = system.file("extdata/data",
                                     "Cal27_NSD1_KO_H3K36me2_10kb_norm_bw.rda",
                                     package = "ChIPbinner"),
  cell_line = "Cal27",
  histone_mark = "H3K36me2",
  annotated_clusters = system.file("extdata/data",
                                   "complete_annotated_clusters.rda",
                                   package = "ChIPbinner"),
  number_of_clusters = 3,
  title_of_plot = "H3K36me2",
  pow = 1.1,
  min_x = -5,
  min_y = -5,
  max_x = 2,
  max_y = 2,
  hexbins = 50,
  show_scales = FALSE,
  xaxis_label = "WT",
  yaxis_label = "NSD1_KO",
  height_of_figure = 6,
  width_of_figure = 15,
  include_additional_density_plot=TRUE,
  filter_extreme_bins = TRUE
)

