norm_bw(out_dir = system.file("extdata",package = "ChIPbinner"),
        genome_assembly = "hg38",
        immunoprecipitated_binned_file = system.file("extdata",
                                            "downsampled.Cal27.WT.H3K36me2.10kb.bed.gz",
                                            package = "ChIPbinner"),
        use_input = TRUE,
        input_binned_file = system.file("extdata",
                                          "downsampled.Cal27.WT_input.H3K36me2.10kb.bed.gz",
                                          package = "ChIPbinner"),
        raw_count_cutoff = 0,
        pseudocount = 1e-3,
        scaling_factor = 0.450328805)
