#!/usr/bin/env Rscript
#' Title
#'
#' @title Generate density-based clusters.
#'
#' @description This function identifies similarly-behaving genomic compartments, such as regions with the highest loss or gain of a specific histone mark.
#'
#' @param path_for_norm_bw Directory where the normalized bigwigs generated by 'norm.bw()' is found.
#' @param out_dir Output directory for the scatterplot.
#' @param treated_samp_label The treated sample name/label.
#' @param baseline_samp_label The baseline sample name/label to which to compare the treated sample. This is usually the wildtype (WT) sample.
#' @param cell_line The cell line of the samples.
#' @param histone_mark The broad histone mark used for the analysis.
#' @param number_of_clusters The total number of clusters identified by the HDBSCAN algorithm.
#' @param annotated_clusters The annotated clusters generated using annotate_clust(), which is an R object that needs to be loaded.
#' @param gene Annotated genic regions in BED format. hg38 and mm10 are included in the package and can be accessed in 'extdata'.
#' @param intergenic Annotated intergenic regions in BED format. hg38 and mm10 are included in the package and can be accessed in 'extdata'.
#' @param title_of_plot The title of the plot.
#' @param window_size The window size in kilobytes. For example, use 10 for samples binned in 10 kilobyte (kb) bins.
#' @param pow The power of. Returns the value of x to the power of y (x^y) and this is used for the scales (i.e. show bins if surpassing a certain intensity). Defaults to 1.25.
#' @param show_legend Boolean term whether to show legend or not.
#' @param min The min for the x and y axis.
#' @param max The max for the x and y axis
#' @param bin_size The number of bins represented by each hexagonal shape.
#' @param show_scales Boolean term whether to show scales or not.
#' @param xaxis_label Label for the x-axis. This is normally the baseline label (i.e. WT)
#' @param yaxis_label Label for the y-axis. This is normally the treated sample label.
#' @param height_of_figure The height of the plot.
#' @param width_of_figure The width of the plot.
#'
#' @return a plot of density-based clusters.
#' @export
#'
#' @include annotate_clust.R
#' @include norm_bw.R
#'
#' @example inst/examples/example_density_based_scatterplot.R
density_based_scatterplot <- function(path_for_norm_bw,
                                      out_dir,
                                      treated_samp_label,
                                      baseline_samp_label,
                                      cell_line,
                                      histone_mark,
                                      annotated_clusters,
                                      number_of_clusters,
                                      gene,
                                      intergenic,
                                      title_of_plot,
                                      window_size,
                                      pow = NULL,
                                      show_legend = FALSE,
                                      min,
                                      max,
                                      bin_size,
                                      show_scales = TRUE,
                                      xaxis_label,
                                      yaxis_label,
                                      height_of_figure,
                                      width_of_figure) {
  # directory parameters
  path <- paste0(path_for_norm_bw)
  out_dir <- paste0(out_dir)
  # samples info
  treated_samp_label <- paste0(treated_samp_label)
  baseline_samp_label <- paste0(baseline_samp_label)
  cell_line <- paste0(cell_line)
  mark <- paste0(histone_mark)
  window_size <- paste0(".", window_size, "kb.")
  # number of cluster
  number_of_clusters <- as.integer(paste0(number_of_clusters))
  # load annotated clusters from using the annotate_clust function
  load(paste0(annotated_clusters))
  # import genic and intergenic reference files
  gene <- rtracklayer::import.bed(gene)
  igr <- rtracklayer::import.bed(intergenic)
  # parameters for plot
  min <- as.numeric(paste0(min))
  max <- as.numeric(paste0(max))
  bin_size <- as.numeric(paste0(bin_size))
  xaxis_label <- paste0(xaxis_label)
  yaxis_label <- paste0(yaxis_label)
  height_of_figure <- as.numeric(paste0(height_of_figure))
  width_of_figure <- as.numeric(paste0(width_of_figure))
  title_of_plot <- paste0(title_of_plot)
  # pow
  if (is.null(pow)) {
    pow <- as.numeric(1.25)
  } else {
    pow <- as.numeric(paste0(pow))
  }
  # list files
  s <- list.files(path = path, pattern = window_size, full.names = FALSE, recursive = FALSE) %>%
    tibble(f = .) %>%
    separate(f, c("line", "samp", "mark", NA, NA, NA), "\\.", F) %>%
    dplyr::mutate(f = file.path(path, f)) %>%
    dplyr::filter(line == cell_line) %>%
    dplyr::filter(samp == baseline_samp_label | samp == treated_samp_label)
  odr <- c(treated_samp_label, baseline_samp_label)
  s <- s %>%
    dplyr::slice(match(odr, samp))
  d <- deframe(s[, c("samp", "f")]) %>%
    lapply(rtracklayer::import.bw)
  # subset by overlaps
  d[[baseline_samp_label]] <- IRanges::subsetByOverlaps(d[[baseline_samp_label]], d[[treated_samp_label]])
  d[[treated_samp_label]] <- IRanges::subsetByOverlaps(d[[treated_samp_label]], d[[baseline_samp_label]])
  lapply(d, length)
  r <- lapply(d, function(y) y[y$score != 0]) %>%
    Reduce(function(a, b) a[IRanges::overlapsAny(a, b)], .) %>%
    GenomicRanges::granges()
  # Initialize an empty list of cluster labels
  clust_labs <- c()

  # Loop to generate lists and append them to master_list
  for (i in 1:number_of_clusters) {
    # Generate a new list (example)
    new_list <- c(toupper(letters[i]))

    # Append new_list to master_list
    clust_labs <- append(clust_labs,new_list)
  }

  # Initialize clus as NA (or any default value)
  clus <- rep("NA", length(r))

  # Loop through each column and update clus if overlap is found
  for (col in clust_labs) {
    if (col %in% names(cons)) {  # Check if column exists in cons
      clus[clus == "NA" & overlapsAny(r, cons[[col]])] <- col
    }
  }

  clus[clus == "NA"] <- NA

  # colours for the clusters
  cclr <- setNames(
    alphabet((number_of_clusters))[seq(1:number_of_clusters)],
    # c("C", "B", "A")
    clust_labs
  )
  # genic and intergenic overlap with enriched regions
  olap <- tibble(
    gene = overlapsAny(r, gene),
    igr = overlapsAny(r, igr)
  ) %>%
    mutate(out = case_when(
      gene & !igr ~ 1,
      !gene & igr ~ -1,
      TRUE ~ 0
    )) %>%
    pull(out)

  lineclr <- "black"
  horz <- F
  gradientn1 <- brewer.rdylbu(50)
  cramp <- colorRampPalette(c("#000000ff", "#ffffff00"), alpha = T)(5)

  leg.brks <- seq(-1, 1, length.out = 19)[seq(2, 18, by = 2)]
  leg.labs <- c(
    sprintf("Genic\u25bc"), rep("", 3), "50%",
    rep("", 3), sprintf("Genic\u25b2")
  )
  len <- 9
  pal <- brewer.rdylbu(len)
  cmat <- seq(0, 255, length.out = len + 1) %>%
    {
      .[-1]
    } %>%
    round() %>%
    as.hexmode() %>%
    format(width = 2, upper.case = T) %>%
    lapply(function(x) {
      paste0(pal, x)
    }) %>%
    do.call(cbind, .) %>%
    data.frame() %>%
    `colnames<-`(1:len) %>%
    mutate(clr = 1:dplyr::n()) %>%
    reshape2::melt(id.vars = "clr", variable.name = "opa") %>%
    mutate(opa = as.integer(opa))
  leg <- ggplot() +
    geom_tile(aes(x = opa, y = clr, fill = value),
      data = cmat
    ) +
    scale_fill_identity() +
    labs(
      x = "# of bins \u25ba",
      y = "% genic \u25ba"
    ) +
    coord_fixed(expand = F) +
    theme(
      panel.background = element_blank(),
      plot.background = element_blank(),
      panel.grid = element_blank(),
      axis.line = element_blank(),
      panel.border = element_rect(colour = "white", fill = NA, size = 0.5),
      axis.ticks = element_blank(),
      axis.text = element_blank(),
      axis.title = element_text(
        family = "Arial",
        color = "white",
        size = 7
      )
    )

  ps <- split(d, s$line) %>%
    lapply(function(x) {
      pdat <- lapply(x[2:1], function(y) {
        IRanges::findOverlaps(r, y) %>%
          to() %>%
          {
            y[.]
          } %>%
          score()
      }) %>%
        bind_cols() %>%
        `names<-`(c("x", "y")) %>%
        mutate(r = olap) %>%
        dplyr::filter(
          x > quantile(x, .01),
          x < quantile(x, .99),
          y > quantile(y, .01),
          y < quantile(y, .99)
        )


      hex <- hexbin(pdat$x, pdat$y, xbins = 75, IDs = T)
      pdat$cell <- hex@cID
      hex <- data.frame(hcell2xy(hex),
        cell = hex@cell,
        count = hex@count
      )

      t1 <- "Intergenic vs genic ratio"
      pdat2 <- pdat %>%
        group_by(cell) %>%
        summarise(prop = mean(r, na.rm = T)) %>%
        ungroup() %>%
        right_join(hex, by = "cell") %>%
        mutate(
          logcount = log10(count),
          ttl = t1
        )
      lim <- data.frame(
        x = c(
          min(pdat2$x[pdat2$count > 10]),
          max(pdat2$x[pdat2$count > 10])
        ) %>%
          scales::expand_range(mul = .05),
        y = c(
          min(pdat2$y[pdat2$count > 10]),
          max(pdat2$y[pdat2$count > 10])
        ) %>%
          scales::expand_range(mul = .05)
      )
      yrang <- diff(lim$y)
      tdat <- data.frame(
        x = rep(median(pdat$x), 2),
        y = rep(median(pdat$y), 2),
        c = c(0, 1),
        ttl = t1
      )
      pow <- pow
      if (show_scales == TRUE) {
        pm <- ggplot() +
          geom_point(aes(x = x, y = y, color = c),
            alpha = 0, data = tdat,
            show.legend = T
          ) +
          geom_hex(aes(x = x, y = y, fill = prop, alpha = count, color = prop),
            stat = "identity", color = NA, data = pdat2, size = 5
          ) +
          scale_fill_gradientn(
            colors = gradientn1, name = "% Genic",
            breaks = leg.brks, labels = leg.labs,
            limits = c(-1, 1)
          ) +
          scale_color_gradientn(
            colors = gradientn1, name = "% Genic",
            breaks = leg.brks, labels = leg.labs,
            limits = c(-1, 1)
          ) +
          scale_alpha(
            range = c(0.01, 1), name = "Number of bins", guide = F,
            trans = scales::trans_new(
              "square",
              function(x) {
                x^(pow)
              },
              function(x) x^(1 / pow)
            )
          ) +
          coord_cartesian(
            expand = F,
            xlim = lim$x,
            ylim = lim$y
          ) +
          facet_grid(. ~ ttl) +
          labs(
            x = sprintf("%s \u25ba", xaxis_label),
            y = sprintf("%s \u25ba", yaxis_label)
          ) +
          annotate("segment",
            x = -Inf, xend = Inf, y = Inf,
            yend = Inf, color = "white"
          ) +
          theme(
            panel.background = element_rect(fill = "black"),
            legend.position = "none",
            panel.grid = element_blank(),
            plot.background = element_blank(),
            legend.background = element_blank(),
            legend.margin = margin(0.015, 0, 0, 0, unit = "npc"),
            axis.line = element_blank(),
            plot.title = element_blank(),
            strip.text = element_text(color = "white"),
            strip.background = element_rect(fill = "black"),
            axis.title = element_text(family = "Arial", color = "black")
          )

        pdat <- kde2d(x = pdat$x, y = pdat$y, n = 100)
        brks <- pretty(c(pdat$z), 30)
        nbrks <- length(brks)
        fac <- diff(brks[1:2]) * nrow(d) / sum(pdat$z)
        b <- isobands(x = pdat$x, y = pdat$y, z = t(pdat$z), brks[1:(nbrks - 1)], brks[2:nbrks])
        bands <- iso_to_sfg(b)
        bdat <- sf::st_sf(level = 1:length(bands), geometry = st_sfc(bands))
        if (!all(st_is_valid(bdat))) {
          bdat <- lwgeom::st_make_valid(bdat)
        }
        bnds <- st_bbox(bdat %>% filter(level > 1))

        bdat$ttl <- title_of_plot
        if (show_legend == FALSE) {
          pl <- ggplot() +
            geom_sf(data = bdat, aes(fill = level), color = NA) +
            scale_fill_gradientn(
              colors = pals::magma(10),
              name = "# of bins \u25ba"
            ) +
            coord_sf(
              expand = F,
              xlim = lim$x,
              ylim = lim$y
            ) +
            labs(
              x = sprintf("%s \u25ba", xaxis_label),
              y = sprintf("%s \u25ba", yaxis_label)
            ) +
            facet_grid(. ~ ttl) +
            guides(fill = guide_colorbar(
              barwidth = 3, barheight = 0.5,
              title.position = "top", title.hjust = 0.5,
              frame.colour = "white", frame.linewidth = 1,
              ticks = F
            )) +
            annotate("segment",
              x = -Inf, xend = Inf, y = Inf,
              yend = Inf, color = "white"
            ) +
            theme(
              panel.background = element_rect(fill = "black"),
              panel.grid = element_blank(),
              plot.background = element_blank(),
              text = element_text(color = "black"),
              legend.title = element_text(
                color = "white", family = "Arial",
                size = 7
              ),
              legend.justification = c(0, 1),
              legend.background = element_blank(),
              legend.position = "none",
              legend.direction = "horizontal",
              legend.text = element_blank(),
              plot.title = element_blank(),
              strip.text = element_text(color = "white"),
              strip.background = element_rect(fill = "black"),
              axis.title = element_text(family = "Arial")
            )
        } else {
          pl <- ggplot() +
            geom_sf(data = bdat, aes(fill = level), color = NA) +
            scale_fill_gradientn(
              colors = pals::magma(10),
              name = "# of bins \u25ba"
            ) +
            coord_sf(
              expand = F,
              xlim = lim$x,
              ylim = lim$y
            ) +
            labs(
              x = sprintf("%s \u25ba", xaxis_label),
              y = sprintf("%s \u25ba", yaxis_label)
            ) +
            facet_grid(. ~ ttl) +
            guides(fill = guide_colorbar(
              barwidth = 3, barheight = 0.5,
              title.position = "top", title.hjust = 0.5,
              frame.colour = "white", frame.linewidth = 1,
              ticks = F
            )) +
            annotate("segment",
              x = -Inf, xend = Inf, y = Inf,
              yend = Inf, color = "white"
            ) +
            theme(
              panel.background = element_rect(fill = "black"),
              panel.grid = element_blank(),
              plot.background = element_blank(),
              text = element_text(color = "black"),
              legend.title = element_text(
                color = "white", family = "Arial",
                size = 7
              ),
              legend.justification = c(0, 1),
              legend.background = element_blank(),
              legend.position = c(0.05, 0.95),
              legend.direction = "horizontal",
              legend.text = element_blank(),
              plot.title = element_blank(),
              strip.text = element_text(color = "white"),
              strip.background = element_rect(fill = "black"),
              axis.title = element_text(family = "Arial")
            )
        }
        pl$coordinates$aspect <- function(f) {
          NULL
        }


        d <- lapply(x[2:1], function(y) {
          IRanges::findOverlaps(r, y) %>%
            to() %>%
            {
              y[.]
            } %>%
            score()
        }) %>%
          bind_cols() %>%
          `names<-`(c("x", "y")) %>%
          mutate(clu = clus) %>%
          dplyr::filter(
            x > quantile(x, .01),
            x < quantile(x, .99),
            y > quantile(y, .01),
            y < quantile(y, .99)
          )

        hull <- na.omit(d) %>%
          group_by(clu) %>%
          dplyr::slice(chull(x, y))
        lab <- na.omit(d) %>%
          group_by(clu) %>%
          summarise(
            x = mean(x),
            y = mean(y)
          )

        bdat2 <- bdat
        bdat2$ttl <- "Density-based clusters"
        d$ttl <- bdat2$ttl[1]
        gradientn <- paste0("#FFFFFF", sprintf("%02X", c(0, round(seq(0, 255, length.out = nbrks - 1)))))
        pr <- ggplot() +
          geom_sf(data = bdat2, aes(fill = level), color = NA) +
          geom_point_rast(
            data = d, aes(x = x, y = y, color = clu),
            alpha = .1, size = .02, raster.dpi = 300,
            raster.height = 5, raster.width = 5
          ) +
          geom_label_repel(
            aes(
              label = clu, x = x, y = y,
              color = clu
            ),
            data = lab,
            show.legend = F,
            point.padding = NA, box.padding = 0,
            direction = "x", inherit.aes = F
          ) +
          scale_fill_gradientn(colors = gradientn) +
          scale_color_manual(values = cclr) +
          coord_sf(
            expand = F,
            xlim = lim$x,
            ylim = lim$y
          ) +
          facet_grid(. ~ ttl) +
          annotate("segment",
            x = -Inf, xend = Inf, y = Inf,
            yend = Inf, color = "white"
          ) +
          labs(
            x = sprintf("%s \u25ba", xaxis_label),
            y = sprintf("%s \u25ba", yaxis_label)
          ) +
          theme(
            panel.background = element_rect(fill = "black"),
            legend.position = "none",
            panel.grid = element_blank(),
            plot.background = element_blank(),
            text = element_text(color = "black"),
            legend.background = element_blank(),
            plot.title = element_blank(),
            strip.text = element_text(color = "white"),
            strip.background = element_rect(fill = "black"),
            legend.margin = margin(0.015, 0, 0, 0, unit = "npc"),
            axis.title = element_text(family = "Arial")
          )
        if (show_legend == FALSE) {
          pr$coordinates$aspect <- function(f) {
            NULL
          }
          # lo <- c(
          #   patchwork::area(t = 1, l = 1, b = 20, r = 20),
          #   patchwork::area(t = 2, l = 2, b = 8, r = 8)
          # )
          # pm_leg <- pm + leg + plot_layout(design = lo)
          patchwork::wrap_plots(pl, pm, pr, nrow = 1)
        } else {
          pr$coordinates$aspect <- function(f) {
            NULL
          } # patchwork::area(t = 1, l = 1, b = 20, r = 20),
          # patchwork::area(t = 2, l = 2, b = 8, r = 8)
          lo <- c(
            patchwork::area(t = 1, l = 1, b = 20, r = 20),
            patchwork::area(t = 2, l = 2, b = 7, r = 7)
          )
          pm_leg <- pm + leg + plot_layout(design = lo)
          patchwork::wrap_plots(pl, pm_leg, pr, nrow = 1)
        }
      } else {
        pm <- ggplot() +
          geom_point(aes(x = x, y = y, color = c),
            alpha = 0, data = tdat,
            show.legend = T
          ) +
          geom_hex(aes(x = x, y = y, fill = prop, alpha = count, color = prop),
            stat = "identity", color = NA, data = pdat2, size = 5
          ) +
          scale_fill_gradientn(
            colors = gradientn1, name = "% Genic",
            breaks = leg.brks, labels = leg.labs,
            limits = c(-1, 1)
          ) +
          scale_color_gradientn(
            colors = gradientn1, name = "% Genic",
            breaks = leg.brks, labels = leg.labs,
            limits = c(-1, 1)
          ) +
          scale_alpha(
            range = c(0.01, 1), name = "Number of bins", guide = F,
            trans = scales::trans_new(
              "square",
              function(x) {
                x^(pow)
              },
              function(x) x^(1 / pow)
            )
          ) +
          coord_cartesian(
            expand = F,
            xlim = lim$x,
            ylim = lim$y
          ) +
          facet_grid(. ~ ttl) +
          labs(
            x = sprintf("%s \u25ba", xaxis_label),
            y = sprintf("%s \u25ba", yaxis_label)
          ) +
          annotate("segment",
            x = -Inf, xend = Inf, y = Inf,
            yend = Inf, color = "white"
          ) +
          theme(
            panel.background = element_rect(fill = "black"),
            legend.position = "none",
            panel.grid = element_blank(),
            plot.background = element_blank(),
            legend.background = element_blank(),
            legend.margin = margin(0.015, 0, 0, 0, unit = "npc"),
            axis.text = element_blank(),
            axis.ticks = element_blank(),
            axis.line = element_blank(),
            plot.title = element_blank(),
            strip.text = element_text(color = "white"),
            strip.background = element_rect(fill = "black"),
            axis.title = element_text(family = "Arial", color = "black")
          )

        pdat <- kde2d(x = pdat$x, y = pdat$y, n = 100)
        brks <- pretty(c(pdat$z), 30)
        nbrks <- length(brks)
        fac <- diff(brks[1:2]) * nrow(d) / sum(pdat$z)
        b <- isobands(x = pdat$x, y = pdat$y, z = t(pdat$z), brks[1:(nbrks - 1)], brks[2:nbrks])
        bands <- iso_to_sfg(b)
        bdat <- sf::st_sf(level = 1:length(bands), geometry = st_sfc(bands))
        if (!all(st_is_valid(bdat))) {
          bdat <- lwgeom::st_make_valid(bdat)
        }
        bnds <- st_bbox(bdat %>% filter(level > 1))

        bdat$ttl <- title_of_plot
        if (show_legend == FALSE) {
          pl <- ggplot() +
            geom_sf(data = bdat, aes(fill = level), color = NA) +
            scale_fill_gradientn(
              colors = pals::magma(10),
              name = "# of bins \u25ba"
            ) +
            coord_sf(
              expand = F,
              xlim = lim$x,
              ylim = lim$y
            ) +
            labs(
              x = sprintf("%s \u25ba", xaxis_label),
              y = sprintf("%s \u25ba", yaxis_label)
            ) +
            facet_grid(. ~ ttl) +
            guides(fill = guide_colorbar(
              barwidth = 3, barheight = 0.5,
              title.position = "top", title.hjust = 0.5,
              frame.colour = "white", frame.linewidth = 1,
              ticks = F
            )) +
            annotate("segment",
              x = -Inf, xend = Inf, y = Inf,
              yend = Inf, color = "white"
            ) +
            theme(
              panel.background = element_rect(fill = "black"),
              panel.grid = element_blank(),
              plot.background = element_blank(),
              axis.text = element_blank(),
              axis.ticks = element_blank(),
              text = element_text(color = "black"),
              legend.title = element_text(
                color = "white", family = "Arial",
                size = 7
              ),
              legend.justification = c(0.1, 1),
              legend.background = element_blank(),
              legend.position = "none",
              legend.direction = "horizontal",
              legend.text = element_blank(),
              plot.title = element_blank(),
              strip.text = element_text(color = "white"),
              strip.background = element_rect(fill = "black"),
              axis.title = element_text(family = "Arial")
            )
        } else {
          pl <- ggplot() +
            geom_sf(data = bdat, aes(fill = level), color = NA) +
            scale_fill_gradientn(
              colors = pals::magma(10),
              name = "# of bins \u25ba"
            ) +
            coord_sf(
              expand = F,
              xlim = lim$x,
              ylim = lim$y
            ) +
            labs(
              x = sprintf("%s \u25ba", xaxis_label),
              y = sprintf("%s \u25ba", yaxis_label)
            ) +
            facet_grid(. ~ ttl) +
            guides(fill = guide_colorbar(
              barwidth = 3, barheight = 0.5,
              title.position = "top", title.hjust = 0.5,
              frame.colour = "white", frame.linewidth = 1,
              ticks = F
            )) +
            annotate("segment",
              x = -Inf, xend = Inf, y = Inf,
              yend = Inf, color = "white"
            ) +
            theme(
              panel.background = element_rect(fill = "black"),
              panel.grid = element_blank(),
              plot.background = element_blank(),
              axis.text = element_blank(),
              axis.ticks = element_blank(),
              text = element_text(color = "black"),
              legend.title = element_text(
                color = "white", family = "Arial",
                size = 7
              ),
              legend.justification = c(0.1, 1),
              legend.background = element_blank(),
              legend.position = c(0.05, 0.95),
              legend.direction = "horizontal",
              legend.text = element_blank(),
              plot.title = element_blank(),
              strip.text = element_text(color = "white"),
              strip.background = element_rect(fill = "black"),
              axis.title = element_text(family = "Arial")
            )
        }
        pl$coordinates$aspect <- function(f) {
          NULL
        }


        d <- lapply(x[2:1], function(y) {
          IRanges::findOverlaps(r, y) %>%
            to() %>%
            {
              y[.]
            } %>%
            score()
        }) %>%
          bind_cols() %>%
          `names<-`(c("x", "y")) %>%
          mutate(clu = clus) %>%
          dplyr::filter(
            x > quantile(x, .01),
            x < quantile(x, .99),
            y > quantile(y, .01),
            y < quantile(y, .99)
          )

        hull <- na.omit(d) %>%
          group_by(clu) %>%
          dplyr::slice(chull(x, y))
        lab <- na.omit(d) %>%
          group_by(clu) %>%
          summarise(
            x = mean(x),
            y = mean(y)
          )

        bdat2 <- bdat
        bdat2$ttl <- "Density-based clusters"
        d$ttl <- bdat2$ttl[1]
        gradientn <- paste0("#FFFFFF", sprintf("%02X", c(0, round(seq(0, 255, length.out = nbrks - 1)))))
        pr <- ggplot() +
          geom_sf(data = bdat2, aes(fill = level), color = NA) +
          geom_point_rast(
            data = d, aes(x = x, y = y, color = clu),
            alpha = .1, size = .02, raster.dpi = 300,
            raster.height = 5, raster.width = 5
          ) +
          geom_label_repel(
            aes(
              label = clu, x = x, y = y,
              color = clu
            ),
            data = lab,
            show.legend = F,
            point.padding = NA, box.padding = 0,
            direction = "x", inherit.aes = F
          ) +
          scale_fill_gradientn(colors = gradientn) +
          scale_color_manual(values = cclr) +
          coord_sf(
            expand = F,
            xlim = lim$x,
            ylim = lim$y
          ) +
          facet_grid(. ~ ttl) +
          annotate("segment",
            x = -Inf, xend = Inf, y = Inf,
            yend = Inf, color = "white"
          ) +
          labs(
            x = sprintf("%s \u25ba", xaxis_label),
            y = sprintf("%s \u25ba", yaxis_label)
          ) +
          theme(
            panel.background = element_rect(fill = "black"),
            legend.position = "none",
            panel.grid = element_blank(),
            plot.background = element_blank(),
            axis.text = element_blank(),
            axis.ticks = element_blank(),
            text = element_text(color = "black"),
            legend.background = element_blank(),
            plot.title = element_blank(),
            strip.text = element_text(color = "white"),
            strip.background = element_rect(fill = "black"),
            legend.margin = margin(0.015, 0, 0, 0, unit = "npc"),
            axis.title = element_text(family = "Arial")
          )
        if (show_legend == FALSE) {
          pr$coordinates$aspect <- function(f) {
            NULL
          }
          # lo <- c(
          #   patchwork::area(t = 1, l = 1, b = 20, r = 20),
          #   patchwork::area(t = 2, l = 2, b = 8, r = 8)
          # )
          # pm_leg <- pm + leg + plot_layout(design = lo)
          patchwork::wrap_plots(pl, pm, pr, nrow = 1)
        } else {
          pr$coordinates$aspect <- function(f) {
            NULL
          }
          lo <- c(
            # patchwork::area(t = 1, l = 1, b = 20, r = 20)
            # patchwork::area(t = 2, l = 2, b = 8, r = 8)
            # https://patchwork.data-imaginist.com/reference/area.html
            # This means that t and l should always be less or equal to b and r respectively
            patchwork::area(t = 1, l = 1, b = 20, r = 20),
            patchwork::area(t = 2, l = 2, b = 7, r = 7)
          )
          pm_leg <- pm + leg + plot_layout(design = lo)
          patchwork::wrap_plots(pl, pm_leg, pr, nrow = 1)
        }
      }
    })
  ggplot2::ggsave((sprintf("%s/%s.%s.%s.%s%sclus.pdf", out_dir, cell_line, baseline_samp_label, treated_samp_label, mark, window_size)), ps[[cell_line]], height = 2.4, width = 6.2, device = cairo_pdf)
  ggplot2::ggsave((sprintf("%s/%s.%s.%s.%s%sclus.png", out_dir, cell_line, baseline_samp_label, treated_samp_label, mark, window_size)), ps[[cell_line]], height = height_of_figure, width = width_of_figure, device = "png", dpi = 600, units = "cm")
  print("Density-based scatterplots generated!")
}
