#!/usr/bin/env Rscript
#' Title
#' @title Merge normalized bigWig files.
#'
#' @description This function will merge normalized bigWig files, which are normally replicates. This function should be used after implementing the 'norm_bw()' function.
#'
#' @param path_for_norm_bw Directory where the normalized bigwigs generated by 'norm.bw()' is found.
#' @param rep1 Replicate 1 to be merged.
#' @param rep2 Replicate 2 to be merged.
#' @param merged_sample_name The sample name of the merged bigWig file.
#' @param cell_line The cell line for the merged bigWig file.
#' @param histone_mark The broad histone mark used for the analysis.
#' @param window_size The window size in kilobytes. For example, use 10 for samples binned in 10 kilobyte (kb) bins.
#' @param out_dir The output directory for merged bigWig files.
#'
#' @return a single merged bigWig file.
#' @export
#'
#' @example
merge_norm_bw <- function(path_for_norm_bw,
                          rep1,
                          rep2,
                          merged_sample_name,
                          cell_line, histone_mark,
                          window_size,
                          out_dir) {
  # example = inst/examples/example_merged_norm_bw.R
  # window size
  window_size <- paste0(".", window_size, "kb.")
  # directory parameters
  path <- paste0(path_for_norm_bw)
  out_dir <- paste0(out_dir)
  # sample info
  cell_line <- paste0(cell_line)
  mark <- paste0(histone_mark)
  rep1 <- paste0(rep1)
  rep2 <- paste0(rep2)
  merged_sample_name <- paste0(merged_sample_name)
  # list files
  s <- list.files(path = path, pattern = window_size, full.names = FALSE, recursive = FALSE) %>%
    tibble(f = .) %>%
    separate(f, c("line", "samp", "mark", NA, NA, NA), "\\.", F) %>%
    mutate(f = file.path(path, f))
  d <- deframe(s[, c("samp", "f")])
  # loop through each file
  bw <- lapply(d, function(x) {
    inp <- import.bw(x)
    return(inp)
  })
  # use one of the replicates' regions as a template
  merged_bw <- bw[[rep1]]
  merged_bw$score <- NULL
  # list scores
  l <- list(bw[[rep1]]$score, bw[[rep2]]$score)
  # Calculate the mean for each row
  row_means <- rowMeans(do.call(cbind, l))
  # Assign the mean values to the 'score' column in 'merged_bw'; the score for the merged bigWig file is now the mean of the the two replicates
  merged_bw$score <- row_means
  # export bw
  export.bw(merged_bw, con = sprintf("%s/%s.%s.%s%snorm.bw", out_dir, cell_line, merged_sample_name, mark, window_size))
}
